### ISSUE TITLE
Allow comparing 2 branches. Base branch can be changed but the current branch is not changable

### ISSUE THREAD

**Issue by yasinarik-talabat** [letmaik/vscode-git-tree-compare#101]
Usecase:

- I work on `branch-a`
- The base branch is `branch-b` (develop, master...)
- There is another branch (like a branch of a colleague) `branch-c`

I want to checkout to `branch-a` to do my work but at the same time, using this extension, I want to see the diff tree between `branch-c` and `branch-b`.

Is this possible? If not, can you please add this?

**Comment by letmaik** [comment]
I'm afraid that's out of scope for this extension. Please use something like GitLens instead.
