### ISSUE TITLE
Support multi-root workspaces

### ISSUE THREAD

**Issue by letmaik** [letmaik/vscode-git-tree-compare#22]
See [workspace.workspaceFolders](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_workspace).

https://github.com/Microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs

**Comment by felixfbecker** [comment]
Yes, please!

**Comment by letmaik** [comment]
This is implemented now and will be part of the next release.
