### ISSUE TITLE
git worktree repositories

### ISSUE THREAD

**Issue by MarekLew** [letmaik/vscode-git-tree-compare#28]
I use `git worktree` and this extension don't work because `.git` is a file not folder.

`.git` file: 
`gitdir: C:/repos/project/src/.git/worktrees/branch1`

At this point, I would only have to set `gitdir` to set the source of the` .git` folder

**Comment by letmaik** [comment]
I just released a bugfix (1.1.3), this should work now. Thanks for reporting!

**Comment by MarekLew** [comment]
Thank you very much. Good job.
