### ISSUE TITLE
Add command/button to open all changed files

### ISSUE THREAD

**Issue by rwu823** [letmaik/vscode-git-tree-compare#29]
Same as Gitlens:

![image](https://user-images.githubusercontent.com/890063/32358419-f2ab026c-c080-11e7-8745-4302d7b69e0c.png)

**Comment by letmaik** [comment]
Great idea. Does the "Open Changed Files" command of GitLens open the diff view or the actual file? I guess you were thinking about opening all diffs right?

**Comment by rwu823** [comment]
@letmaik I'd like to have both. Actually GitLens also have both commands.

![image](https://user-images.githubusercontent.com/890063/32415172-5199c128-c270-11e7-90d2-f5ab62534179.png)


Thanks for your hard work.

**Comment by letmaik** [comment]
Added in the latest release of the extension.
