### ISSUE TITLE
not working with latest update?

### ISSUE THREAD

**Issue by temelj** [letmaik/vscode-git-tree-compare#34]
this extension seems to be broken at the moment.

Visual Studio Code 1.20.1 (latest)

**Comment by temelj** [comment]
I'd like to add a small update to this:
Could it possibly be true that if a current local branch is too far off the base branch (selected in the tool)

that the changes don't show up?

**Comment by letmaik** [comment]
The changes should always show up, no matter how far apart the refs are.
There's a bugfix in the latest unreleased VS Code which may be related to that. If you like, can you please try it in VS Code Insiders https://code.visualstudio.com/insiders/? It installs side-by-side and doesn't cause any changes to the regular VS Code installation. If that works, then we know what it is.

**Comment by temelj** [comment]
Will try tomorrow.

It has started working for me after I merged from our master branch. There were lots of changes so I was just guessing that it may have something to do with the number of files or something.

**Comment by letmaik** [comment]
Hmm, do you know roughly how many changed files we're talking about?

**Comment by temelj** [comment]
270+

**Comment by temelj** [comment]
Just to give you an update:
I've got the VSCode Insiders 1.21.0-insider and the extensions and I can see it working fine

I've also got VSCode 1.20.1 and it is not showing me any files in the Git Tree Compare.

Just to put this in perspective - the Branch has 354 files changed with 250+ commits

**Comment by letmaik** [comment]
OK then it's probably that. It's a bug in tree data fetching. The next VS Code release will be in 2 weeks, so let's hope that fixes these issues.

**Comment by temelj** [comment]
thanks for the quick responses.  great and useful tool :)

**Comment by letmaik** [comment]
@temelj Is this fixed for you with the current VS Code version?

**Comment by temelj** [comment]
Works as advertised. 
Thank you for the support. 

I installed GitLens on VS insider and found it slower than git tree compare. It has heaps of features, might explain performance :)
