### ISSUE TITLE
I don't have any icons showing up at this time. 

### ISSUE THREAD

**Issue by jacobrillema** [letmaik/vscode-git-tree-compare#35]
Version 1.21.0-insider
Commit 3fec61014742dec894b3a31cdf8556bf533cb0e1
Date 2018-02-28T05:17:16.839Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by letmaik** [comment]
Which OS are you on and which git version do you have installed?
