### ISSUE TITLE
Superfluous diff entry if file only gets touched

### ISSUE THREAD

**Issue by letmaik** [letmaik/vscode-git-tree-compare#37]
See https://stackoverflow.com/questions/36367190/git-diff-files-output-changes-after-git-status
Currently the extension uses `diff-index` without `update-index --refresh`.
I saw this happen once with an `__init__.py` file without having it touched myself, must have been some tool. In that case, the file content was the same but the file time had changed.
Since this would not normally happen I'm reluctant to add another git invocation.
If anyone else observes this, please comment here.

**Comment by tolu** [comment]
I think I have this very problem. It seems to me that all files are always reported as changed in my case 😢

**Comment by letmaik** [comment]
@tolu Thanks for reporting. Can you manually check if the file times are not what you expect? Can you think of any tool on your system that would touch all files?

**Comment by letmaik** [comment]
This also happens when a file is changed and the change is manually undone (in the editor), without using the revert button on the scm view (or the git cli). Then the timestamp would also be different.

**Comment by letmaik** [comment]
This is now implemented, together with config option to disable the automatic index refreshing which may be useful for very large repositories to avoid slowdowns. Will be part of the next version.
