### ISSUE TITLE
Feature Request: Move Tree Compare to the Activity Bar

### ISSUE THREAD

**Issue by tobiastom** [letmaik/vscode-git-tree-compare#39]
Version 1.23 introduced [Contributions to the Activity Bar](https://code.visualstudio.com/updates/v1_23#_contributions-to-the-activity-bar).

With that change the Git Tree Compare view should be moved to a separate item inside the bar.

**Comment by letmaik** [comment]
I think it should move to the source control view instead of a new one.

**Comment by tobiastom** [comment]
If I read the blog post correctly the activity bar seems to be the place to expose things like that, but inside the source control view is also fine for me.

**Comment by borekb** [comment]
GitLens moved most of its panel to the SCM view recently and since then, I also always look for the Git Tree Compare panel there :) Would be great to have this moved or at least configurable.

**Comment by rwu823** [comment]
Hi @letmaik 

I think it should be configurable for user, it has benefits locate in  Activity Bar.

![image](https://user-images.githubusercontent.com/890063/42788935-055e23ac-8995-11e8-9a89-a4f28c5a9127.png)

Such as we can define shortcut or search commands for Activity Bar

![image](https://user-images.githubusercontent.com/890063/42789065-b8d4b8ec-8995-11e8-9610-64575807d387.png)

**Comment by letmaik** [comment]
@rwu823 PR welcome :)
