### ISSUE TITLE
command 'gitTreeCompare.openAllChanges' not found

### ISSUE THREAD

**Issue by subni9** [letmaik/vscode-git-tree-compare#40]
I am getting command not found for any of the git tree commands...

**Comment by edmundnoble** [comment]
Same here. Not sure if I'm using the plugin incorrectly, because there are no instructions, but all of the plugin commands give "command not found".

**Comment by edmundnoble** [comment]
@letmaik I'm using the launcher thing to type the command in; not sure which UI you mean.

**Comment by gmellado** [comment]
Im having same problem. Git compare "tab" is not in the main page anymore. In fact, it can change base but is not reading from it so it says no changes. And now, that tab is only present in git tab and not in the editor view tab.

**Comment by letmaik** [comment]
@gmellado See #39, the move was on purpose.
Are you guys by any chance using workspaces with multiple folders?

**Comment by chrislandeza** [comment]
What happen to this plugin? It's not even showing on the exlorer tab.

**Comment by chrislandeza** [comment]
ohh, so it's on the Source Control Panel now (ctrl+shift+G). This should be configurable :(

**Comment by futurist** [comment]
+1 for this

after installed this extension, then press `Cmd+Shift+P`, input `> git tree`, all the commands cannot run.

After press `Ctrl+Shift+G` switched to Source Control Panel, Change a base, then all the commands in  command palette can be run.

**Comment by briancodes** [comment]
@futurist I tried going to Source Control Panel, then `Ctrl+Shift+P`>`Git Tree Compare: Change Base...`, but get the error `command 'gitTreeCompare.changeBase' not found`. Is this the same as the process you used?

**Comment by letmaik** [comment]
I added some changes such that invoking commands is possible for the case when the extension isn't activated yet. Any command will now activate the extension. Note that there was no easy way to make the tree view visible (expand it) in this case, so to avoid confusion I show a message a la "Git Tree Compare is hidden! Look for it in the ${tab} tab.". This should help new users to figure out what's going on when they haven't discovered the tree view yet, which by the way I think is the main way one should interact with this extension, not via commands from the command palette, but ok, it's possible now anyway even in the described special case. This will be part of the next version.
