### ISSUE TITLE
Changed files suddenly stopped showing on git compare tree when...

### ISSUE THREAD

**Issue by ojikobeshi** [letmaik/vscode-git-tree-compare#41]
I was working with a laravel project using composer and I've narrowed down the behaviour due to a generated  composer.lock file

Basically, I compare my current branch against remote branch where
- current git branch: composer.lock was removed
- remote git branch: still has the composer.lock file
- composer.lock was reintroduced due to composer install/update

Quick fix is to remove the composer.lock or rename it but I assume a similar occasion occurred due to a similar behaviour (and I just did not figure out the cause) with other tracked/untracked files.

**Comment by letmaik** [comment]
Is the reintroduced composer.lock file identical to what is in the remote branch? If yes, then the behaviour is correct, otherwise not.

**Comment by ojikobeshi** [comment]
Thank you for the feedback. I have not verified if there's an actual difference but the issue I'm referring to here is for the entire tree diff. If composer.lock has same content as remote branch, it should not prevent diff of other files from showing up. In my case, there are quite several of them.

**Comment by letmaik** [comment]
I see, yes, that shouldn't happen. I'll try to reproduce it, but just in case I can't, can you make a copy of the folder which shows this issue in case we need it later on?

**Comment by ojikobeshi** [comment]
Sure and thanks!

**Comment by letmaik** [comment]
Just wanted to report back that I can reproduce it. Let's see what's going on here...

**Comment by letmaik** [comment]
This is fixed now, I'll do a new release soon. Thanks again for reporting, great job on narrowing it down so much! :)
