### ISSUE TITLE
Allow setting arbitrary commit as comparison base

### ISSUE THREAD

**Issue by pimlottc-gov** [letmaik/vscode-git-tree-compare#42]
The "Change Base" dialog only lets me enter refs (such as branches or tags) as a base for comparison.  I should be able to enter any arbitrary commit hash.  It doesn't need to list all the hashes, just allow me to enter one manually.

**Comment by letmaik** [comment]
This is implemented now and will be part of the next release:
![image](https://user-images.githubusercontent.com/530988/47118530-6d2a1280-d25f-11e8-9055-5f127f9be6f0.png)

![image](https://user-images.githubusercontent.com/530988/47118542-774c1100-d25f-11e8-8abe-b4b575ed03d9.png)
