### ISSUE TITLE
Support full diff between two branches instead of merge diff

### ISSUE THREAD

**Issue by Philippe-Collignon** [letmaik/vscode-git-tree-compare#44]
Hello,

When I compare to another branch (Changing base) the result is a comparison but not with the last commit of the other branch ?!

git version 2.17.1
vscode Version: 1.28.2
OS: Linux x64

**Comment by Philippe-Collignon** [comment]
Sorry .. it's working as excpected I was wrond

**Comment by Philippe-Collignon** [comment]
Ok I get it .. it's because master is not the default branch ... so it compares with the last commit when master was the default branch ..

**Comment by letmaik** [comment]
I decided to implement this (as a diff mode option) as it turned out to be easy. Will be part of the next release.

**Comment by Philippe-Collignon** [comment]
Hello, Thanks for your feedback.
To answer your question, this is the case for which I would need that feature : 
Let us have two versions or an application  : version "demo" and version "full".  
Both have common files in "master" but some are specific to the versions.
So I use git to handle this.  There are two branches "demo" and "full",
they are always separated and sometime I merge common changes from "master".
But before merging, I want to check differences between demo, master and full; 
just to be sure git merge is not going to do something I was not expecting.

**Comment by letmaik** [comment]
Thanks for the explanation. I think the new feature would handle this, since it would should you what exactly would be merged in from master if you are on the demo branch let's say.
