### ISSUE TITLE
Add button to quickly open a file

### ISSUE THREAD

**Issue by borekb** [letmaik/vscode-git-tree-compare#46]
Clicking a file open its diff which is consistent with what the built-in Git / SCM view does. However, on hover, they also show a button to open a file instead:

<img width="327" alt="Screenshot 2019-03-16 at 22 37 45" src="https://user-images.githubusercontent.com/101152/54481968-26573d80-483c-11e9-980b-3bdee588aaaf.png">

It's quite useful, do you think it could be added to this extension as well? Right now, the way to do it is to right-click the file and select _Open File_.

Thanks!

**Comment by letmaik** [comment]
Great suggestion, I implemented it and it'll be part of the next release.

**Comment by borekb** [comment]
Awesome, thank you!
