### ISSUE TITLE
Handle projects with git sub modules - tree view empty

### ISSUE THREAD

**Issue by friedger** [letmaik/vscode-git-tree-compare#53]
My project contains a submodule. The tree compare view is empty. Other git extensions ask me which repository should be used.

Do you support projects with submodules?

```
I see an error method like:
Error: Could not determine commit for "heads/v1.3.3"
	at Object.module.exports.t.getBranchCommit 
```

**Comment by letmaik** [comment]
Submodules are not currently supported. The extension only scans the first folder level for additional repositories, for each workspace folder. The code is here: https://github.com/letmaik/vscode-git-tree-compare/blob/fe22abd2a1a027509b16759b6f1cb03939ac5f64/src/gitHelper.ts#L48-L81

**Comment by friedger** [comment]
@letmaik Could the extension at least show the top level changes? Currently, it does not show any changes at all.

**Comment by letmaik** [comment]
Sorry I don't quite follow, but please open a separate issue if it's not related to submodules.

**Comment by friedger** [comment]
@letmaik I think it is related to submodules, do you have any suggestion how to further debug the issue?

**Comment by letmaik** [comment]
You could look at the log in the Output tab. That should give enough information what's going wrong.

**Comment by friedger** [comment]
The problem was that I add ambigious branch/tag names. One tag with the same name as the current branch. The extension didn't like that.
