### ISSUE TITLE
"Invalid git URI" in VSCode 1.41

### ISSUE THREAD

**Issue by borekb** [letmaik/vscode-git-tree-compare#55]
After the latest update, trying to open diff from the Git Tree Compare view fails with:

```
Unable to open 'file.ts (Working Tree)': Invalid git URI: missing path.
```

In v1.41 release notes, I noticed [this note](https://code.visualstudio.com/updates/v1_41#_git-adoption-of-filesystemprovider):

> The Git extension now uses the FileSystemProvider API which, besides fixing certain encoding issues, provides a more performant and more reliable way of exposing older versions of your files, from a Git repository.

Could it be related?

**Comment by letmaik** [comment]
This is fixed now and I released a bugfix release. Let me know if there are any other issues.

**Comment by borekb** [comment]
Works great, thank you for a quick fix!
