### ISSUE TITLE
Tree is not visible: "TypeError: Cannot read property 'size' of undefined"

### ISSUE THREAD

**Issue by letmaik** [letmaik/vscode-git-tree-compare#57]
@vazmike wrote: 
![image](https://user-images.githubusercontent.com/530988/73246462-9ba6d500-41a6-11ea-8afe-f9b0db08feab.png)

https://github.com/letmaik/vscode-git-tree-compare/files/4089870/-1579594405343.log

@lsdev14 wrote:
> I'm getting the same problem. I'm not sure, but I think it started happening after the last update from git on windows, 2.25.0

After updating git from 2.22.0 to 2.25.0 I was able to reproduce this as well, although with slightly different error message:
```
Error: Could not find any workspace folder for C:\Users\..\git\vscode-git-tree-compare in c:\Users\..\git\vscode-git-tree-compare
	at Object.t.getWorkspaceFolders (c:\Users\..\.vscode\extensions\letmaik.git-tree-compare-1.7.1\dist\extension.js:1:29760)
	at _.setRepository (c:\Users\..\.vscode\extensions\letmaik.git-tree-compare-1.7.1\dist\extension.js:1:53630)
	at async c:\Users\..\.vscode\extensions\letmaik.git-tree-compare-1.7.1\dist\extension.js:1:51114

Ignoring updateDiff() error during handleWorkspaceChange() TypeError: Cannot read property 'size' of undefined
	at _.updateDiff (c:\Users\...\.vscode\extensions\letmaik.git-tree-compare-1.7.1\dist\extension.js:1:60594)
```

**Comment by letmaik** [comment]
@vazmike @lsdev14 Could you try the new version on Insiders and let me know if you still see the error?

**Comment by VazMike** [comment]
Yes, it works on Insiders! Thank you!

Great extension, much less noise than in Get Lens 👍

**Comment by lsdev14** [comment]
> 
> 
> @VazMike @lsdev14 Could you try the new version on Insiders and let me know if you still see the error?

Yes, it works om Insiders!
Thanks you
