### ISSUE TITLE
Tree not updated after refresh

### ISSUE THREAD

**Issue by letmaik** [letmaik/vscode-git-tree-compare#64]
The log indicates that the right git commands are run and the reported number of diff entries matches reality, but then "No tree changes" is printed and the tree is not updated.

**Comment by segfault16** [comment]
Hi, I'm having the same issue

**Comment by letmaik** [comment]
@segfault16 If you can figure out how to make this reproducible (with a fresh repository) then I could potentially fix it.

**Comment by letmaik** [comment]
This should be solved now. The previous complex and likely faulty algorithm that partially updated tree nodes has been removed in favor of a simpler full refresh (which was already used for the new compacted and list modes). While this increases resource usage for very big diffs (hundreds of files) when having auto refresh enabled and causing tree changes, this scenario is sufficiently rare that it is not worth the effort of maintaining that complex code. On top of that, temporarily disabling auto refresh for such edge cases is always an option.
