### ISSUE TITLE
Git tree is hidden

### ISSUE THREAD

**Issue by JSebastianN** [letmaik/vscode-git-tree-compare#65]
I get this error.

![image](https://user-images.githubusercontent.com/6465685/76559398-64169280-649f-11ea-9baf-b6e813eb0301.png)

But there is no tab in the explorer.

**Comment by letmaik** [comment]
This message is displayed when you manually invoked a Git Tree Compare command while the extension is hidden. I guess the text should say something like "Right-click in the explorer tab header to make it visible" or similar. Does that help?

**Comment by JSebastianN** [comment]
Ah, it's in the Source Control tab, not explorer.

Next question:
There is no contents. I have a repository open and changes made...
What am I missing?

Change base gives the error "No repository selected"

**Comment by letmaik** [comment]
There's currently a timing bug that needs to be fixed which may cause this issue. Can you restart VS Code and see if that fixes it?

**Comment by letmaik** [comment]
Closing this as I have removed the confusing info message in 84de26eac59f9bc21a6b7737c5b7ea98eed1f37a. Feel free to open a new issue if you still see problems.
