### ISSUE TITLE
Show refresh icon even if auto-update is enabled

### ISSUE THREAD

**Issue by ashamis** [letmaik/vscode-git-tree-compare#66]
Can you please add a refresh icon where the next to the "Change Base" icon

![image](https://user-images.githubusercontent.com/887483/76781316-739b2180-67a6-11ea-89a0-217af88fcf25.png)

**Comment by letmaik** [comment]
The refresh icon is displayed automatically if auto-refresh is turned off. Do you see an issue where the tree is not refreshed properly even with auto-refresh enabled (default)?

**Comment by ashamis** [comment]
It does not auto refresh correctly when I am jumping between branches using the command-line.

Repo steps:

1 - working on branch A, I have some upstaged changes there
2 - stash some changes
3 - change to branch B

Occasionally the plugin would show me a diff as if I was on step (1)

**Comment by letmaik** [comment]
I'll reach out to you directly to try to repro and understand what's going wrong with the auto-update, but I think your point of adding the refresh icon makes sense anyway, even if auto-refresh is enabled. This follows the same behaviour of the refresh icon of the VS Code built-in git extension, which may not auto-update (even if enabled) for various reasons, e.g. if the system limit of inode file watchers is reached, and thus there is still value in manual refreshes.

**Comment by letmaik** [comment]
Icon is now always shown. df996941afd642edea73319a2554e8b0732e90e6
