### ISSUE TITLE
Drag And Drop Files

### ISSUE THREAD

**Issue by VazMike** [letmaik/vscode-git-tree-compare#67]
Having more than 1 group editors is a useful feature.
I often create groups by dragging files from Explorer and dropping them near the edge of the editor.

Wouldn't you consider adding this feature for files in Git Tree Compare view?

**Comment by letmaik** [comment]
Sorry, I don't quite understand what you mean.

**Comment by VazMike** [comment]
![image](https://user-images.githubusercontent.com/14861435/79037836-31b29f00-7bdd-11ea-9348-d1d7cc2a5271.png)

I just found out that what I'm asking is not supported even in built-in Source Control view.
It is not very useful anyway.

Thank you.
