### ISSUE TITLE
is it possible to focus current opened file in the list ?

### ISSUE THREAD

**Issue by ctf0** [letmaik/vscode-git-tree-compare#73]
similar to how the scm default view list works.

> this is mostly when using any of the open in bulk cmnds ex.`open changed files`

**Comment by stevenqzhang** [comment]
Sorry newbie question- which command is this implemented as? I don't see this issue linkedin to a PR. context is I was looking for this feature :) @ctf0

**Comment by ctf0** [comment]
i honestly cant remember + i dont use the extension anymore

**Comment by stevenqzhang** [comment]
np. just curious- what extension do you use to diff against main?
