### ISSUE TITLE
Sidebar/panel icon

### ISSUE THREAD

**Issue by jaywick** [letmaik/vscode-git-tree-compare#74]
When you move the git-tree-compare panel out and for example onto sidebar, the standard git icon is shown.

![image](https://user-images.githubusercontent.com/3955052/101411314-e059db80-3934-11eb-9fd4-20702199946d.png)

There are some other [codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html) we can use cheaply to differentiate the views.

![image](https://user-images.githubusercontent.com/3955052/101411406-097a6c00-3935-11eb-9e5d-6880c428031a.png)

Happy to make a PR if there's a preferred icon (mine is `git-compare` 😁)

**Comment by letmaik** [comment]
Thanks for the suggestion, I agree that's a bit weird, but hey, back when I created the extension you couldn't even drag it out! `git-compare` seems to make the most sense, since it's also the top-level icon in the tree. PR welcome :)

**Comment by jaywick** [comment]
PR is up #77!
