### ISSUE TITLE
[Feature Request] Setting to show collapsed

### ISSUE THREAD

**Issue by lonix1** [letmaik/vscode-git-tree-compare#78]
Thank you for this nice extension!

It would be nice to have a setting that shows the tree as initially *collapsed*. (Right now when one opens the panel it shows the tree as expanded.)

**Comment by letmaik** [comment]
If I understand correctly then you want all folders, including subfolders, initially collapsed. And then you would manually expand them as needed. Is this right?

This wouldn't be hard to implement but I'm struggling to see the value of it. Could you give some examples on where the current behaviour seems too annoying in your case?

**Comment by lonix1** [comment]
Correct.

For a large feature branch, when there are dozens of modified files in dozens of namespaces (or across projects - I'm using dotnet BTW), the panel is very "long" and it's hard to find anything.

I know what you're thinking: a feature branch should never get too big, but... it happens. :)

**Comment by letmaik** [comment]
OK, makes sense. I think ideally I instead would like to add support for on-demand collapsing (new button), like in vs code's explorer. Unfortunately, the extension API doesn't support that yet: https://github.com/microsoft/vscode/issues/92176.

**Comment by letmaik** [comment]
I pushed a new version with the feature, can you give it a try?

**Comment by lonix1** [comment]
Awesome addition to an awesome extension!

Note I couldn't get it to work initially, but then realized I should probably restart vscode! Might make a note of that in the docs?

I also upvoted that upstream issue.

Thanks!
