### ISSUE TITLE
keyboard shortcut

### ISSUE THREAD

**Issue by mariusa** [letmaik/vscode-git-tree-compare#82]
Hi, 

Since I had the activity bar hidden, it was quite hard to discover how to use this extension. Had to browse through other issues to find out. The Marketplace page could say "In Activity bar, look for this icon". Instead of the current drag'n'drop which I can't tell where to start dragging from.

Anyways. It would be great to have a keyboard shortcut to activate it too, without having to click on activity bar.
There's already a shortcut for 'Ctrl Shift G G'. Maybe use 'Ctrl Shift G C' ?

**Comment by letmaik** [comment]
In the "Location" section in the README the first sentence is "By default, the tree view is located in its own container accessible from the activity bar on the left. ". Would you rephrase that?

Regarding the keyboard shortcut, there's no default but you can configure your own:

![image](https://user-images.githubusercontent.com/530988/143656106-8c32774d-4fc4-4e49-aadb-fc90e6b6a398.png)

**Comment by mariusa** [comment]
I'm sorry, you're right. I kept staring at the animated gif instead of reading.

Thanks for the tip on how to set a keyboard shortcut!
