### ISSUE TITLE
Jump to file not command not working as expected?

### ISSUE THREAD

**Issue by tnrich** [letmaik/vscode-git-tree-compare#84]
Hey there! Thanks again for this great extension! 

I am trying to jump to the changes view using the 'Git Tree Compare: Open Changes' command while inside a file with changes.

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/2730609/156235528-ab2400f7-9074-4d12-b036-c0d49547b63e.png">

However it doesn't seem to be working and is confusingly asking me to right click on a file instead: 
<img width="533" alt="image" src="https://user-images.githubusercontent.com/2730609/156235561-6ce4b674-5d90-48a3-a92d-abed68dade7e.png">

Can this be fixed or can you please add a way to open the changes for a given file. 

Thanks again!
Thomas

**Comment by letmaik** [comment]
The commands are not meant to be invoked from the command palette. If you click on the file in the tree view then it shows the diff. Are you saying this is too annoying since you need to find the file in the list again?

**Comment by tnrich** [comment]
@letmaik I think it would be really nice to be in a file that has been changed compared to master and to be able to jump to the diff view between the file and master. Does that make sense?

It would work basically the same as `Git: Open Changes` does: 
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/2730609/156417104-c5010be6-e181-41f8-b3cf-58daefb19a66.png">
which jumps you to the changes view: 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2730609/156417157-e29f8dd7-6caa-416a-97c8-6816330b326e.png">

**Comment by letmaik** [comment]
Part of 1.14.0. I also added support for "Open File", for the case when you're in the diff editor.

**Comment by tnrich** [comment]
@letmaik awesome thank you so much for these changes! Definitely improves my workflow!
