### ISSUE TITLE
Feature Request - Add little "Reset Button to Main/Master/XXX" helper buttons next to each file

### ISSUE THREAD

**Issue by tnrich** [letmaik/vscode-git-tree-compare#90]
Hi there, again thanks for the great extension, I use it all the time! 

One thing that would make it even better would be if you could add helper buttons next to the files a la the built in vscode diff view:
<img width="528" alt="image" src="https://user-images.githubusercontent.com/2730609/236573006-4ac8e1b8-6b63-4b85-85f9-4a2568273676.png">

Right now there is only an open file button. In particular I think there should be a button to "Reset File to Master" next to each file: 
![image](https://user-images.githubusercontent.com/2730609/236573122-8630f1ce-6adb-44e4-871e-1eba53adda56.png)

Thanks!

**Comment by letmaik** [comment]
What is the git command you would run on the command line to revert a file to a given base ref? How would you deal with path renames?

**Comment by tgreen7** [comment]
```git checkout origin/master [filename]``` will revert file changes. This wouldn't handle renames though.

**Comment by tnrich** [comment]
Wow @letmaik that was quick 🙏🤙🥴

**Comment by letmaik** [comment]
I went ahead and implemented this in #91. It wasn't hard but there are a bunch of special cases to deal with. I pushed out a new release, let me know if you see any issues that should be fixed.

**Comment by tnrich** [comment]
Working awesome so far @letmaik ! Really appreciate it!
