### ISSUE TITLE
Does `virtualWorkspaces` needs to be `false`?

### ISSUE THREAD

**Issue by xunilrj** [letmaik/vscode-git-tree-compare#94]
Any reason `virtualWorkspaces` is not enabled? I manually put `true` and everything is working.
This makes the extension not available in a lot of scenarios.

https://github.com/letmaik/vscode-git-tree-compare/blob/master/package.json#L35

**Comment by letmaik** [comment]
I'm not sure how the extension would work with virtual workspaces since it invokes the git binary and relies on an actual filesystem instead of a filesystem provider. Can you provide more details about your scenario?

**Comment by xunilrj** [comment]
If you start https://github.com/gitpod-io/openvscode-server, open the browser version of vscode and search for this extension, it does not appear. I think this happens because `virtualWorkspaces` is false.

But manually installing the `vsix`, the extension works.

**Comment by letmaik** [comment]
If it's running a full VS Code server like Codespaces then `virtualWorkspaces` isn't supposed to be `true`. Looks like a bug to me on their end. Feel free to raise the issue there and mention this issue.
