### ISSUE TITLE
Remoting from Windows to Linux fails

### ISSUE THREAD

**Issue by StephenHillAtViaivi** [letmaik/vscode-git-tree-compare#95]
I run VsCode in Windows and remote into a Linux VM which contains a repo.
When I  do this, the extension does not work.
When I hit refresh I see the following in the output log:
`Using git from git`
`Updating the git tree failed: The "path" argument must be of type string. Received undefined`
Trying 'Change Base...' produces the error:
`No repository selected`

**Comment by letmaik** [comment]
I have no issues using the remote extensions. Can you confirm that this is not the same issue as #87 where you try to open VC Code from the command line?

**Comment by StephenHillAtViaivi** [comment]
It turns out that ... we were using a symbolic link to the repo via VsCode ... when we instead use the 'real' path everything is fine.
